-- 20260430100000_create_shipping_fee_config.sql
-- Phase 1 — Quick Order Mobile Redesign
-- Bảng config phí ship flat rate per method (không zone, không weight).
-- Admin update qua SQL/Studio (Phase sau có CRUD UI nếu cần).

BEGIN;

CREATE TABLE IF NOT EXISTS public.shipping_fee_config (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  delivery_method text NOT NULL CHECK (delivery_method IN ('cod', 'company_delivery', 'pickup')),
  flat_fee numeric NOT NULL DEFAULT 0 CHECK (flat_fee >= 0),
  estimated_days_min int NOT NULL DEFAULT 0 CHECK (estimated_days_min >= 0),
  estimated_days_max int NOT NULL DEFAULT 0 CHECK (estimated_days_max >= 0),
  estimated_text text,
  is_active boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT shipping_fee_config_method_unique UNIQUE (delivery_method)
);

ALTER TABLE public.shipping_fee_config ENABLE ROW LEVEL SECURITY;

-- Public READ — config dùng cho cả khách chưa login khi xem checkout preview sau này.
CREATE POLICY "shipping_fee_config_read_all" ON public.shipping_fee_config
  FOR SELECT USING (true);

-- WRITE chỉ service_role (mặc định bypass RLS). Không tạo policy WRITE → block authenticated user.

-- Seed values (PROPOSED — sếp Nam Việt confirm số thật trước khi merge prod).
INSERT INTO public.shipping_fee_config (delivery_method, flat_fee, estimated_days_min, estimated_days_max, estimated_text)
VALUES
  ('cod', 50000, 1, 2, 'Hôm nay đặt, mai nhận'),
  ('company_delivery', 0, 0, 3, 'Theo lịch tuyến giao'),
  ('pickup', 0, 0, 0, 'Sẵn hàng hôm nay sau 18:00')
ON CONFLICT (delivery_method) DO NOTHING;

COMMENT ON TABLE public.shipping_fee_config IS 'Phí ship flat rate per method. Phase 1 — không zone, không weight. Admin update qua SQL/Studio.';

COMMIT;
