//src/shared/lib/constants.ts
export const Constants = {
  public: {
    Enums: {
      account_balance_type: ["No", "Co", "LuongTinh"],
      account_status: ["active", "inactive"],
      account_type: [
        "TaiSan",
        "NoPhaiTra",
        "VonChuSoHuu",
        "DoanhThu",
        "ChiPhi",
      ],
      appointment_service_type: ["examination", "vaccination"],
      appointment_status: [
        "pending",
        "confirmed",
        "completed",
        "cancelled",
        "checked_in",
      ],
      asset_status: ["active", "storage", "repair", "disposed"],
      business_type: ["trade", "advance", "reimbursement", "internal", "other"],
      customer_b2c_type: ["CaNhan", "ToChuc"],
      customer_gender: ["Nam", "Nß╗»", "Kh├íc"],
      employee_status: ["pending_approval", "active", "inactive"],
      fund_account_status: ["active", "locked"],
      fund_account_type: ["cash", "bank"],
      maintenance_exec_type: ["internal", "external"],
      order_status: [
        "DRAFT",
        "QUOTE",
        "QUOTE_EXPIRED",
        "CONFIRMED",
        "PACKED",
        "SHIPPING",
        "DELIVERED",
        "CANCELLED",
      ],
      queue_priority: ["normal", "high"],
      queue_status: ["waiting", "examining", "completed", "skipped"],
      service_package_type: ["service", "bundle"],
      shipping_partner_type: ["app", "coach", "internal"],
      stock_management_type: ["lot_date", "lot_only", "serial", "simple"],
      template_module: [
        "pos",
        "b2b",
        "hr",
        "appointment",
        "accounting",
        "general",
      ],
      template_type: ["print", "pdf", "email", "sms"],
      transaction_flow: ["in", "out"],
      transaction_status: [
        "pending",
        "confirmed",
        "cancelled",
        "completed",
        "approved",
      ],
      transaction_type: ["thu", "chi"],
    },
  },
} as const;
