// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/ai/chat": {
            "post": {
                "description": "Gửi câu hỏi cho AI và nhận câu trả lời dạng Server-Sent Events (SSE)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "System"
                ],
                "summary": "AI Chatbot Streaming",
                "parameters": [
                    {
                        "description": "Chat request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.AIChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE Stream",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/clinic/appointments": {
            "post": {
                "description": "Lễ tân tạo lịch hẹn khám bệnh cho bệnh nhân",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clinic"
                ],
                "summary": "Đặt lịch khám",
                "parameters": [
                    {
                        "description": "Book appointment request payload",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.BookAppointmentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Appointment"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/clinic/appointments/{id}/check-in": {
            "post": {
                "description": "Lễ tân xác nhận bệnh nhân đã tới và đưa vào hàng đợi chờ khám",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clinic"
                ],
                "summary": "Bệnh nhân Check-in",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Appointment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Check-in request payload",
                        "name": "req",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/domain.CheckInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/crm/loyalty/earn": {
            "post": {
                "description": "Cộng điểm cho khách hàng dựa trên giá trị đơn hàng",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CRM"
                ],
                "summary": "Tích điểm thành viên",
                "parameters": [
                    {
                        "description": "Earn loyalty request payload",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.EarnLoyaltyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/finance/transactions": {
            "post": {
                "description": "Sinh phiếu thu chi, tự động chặn nếu vi phạm luật thuế, chẻ phiếu nếu lệch tiền",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Finance"
                ],
                "summary": "Tạo giao dịch thu/chi",
                "parameters": [
                    {
                        "description": "Create transaction request payload",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/finance/vat-allocation": {
            "post": {
                "description": "Sử dụng thuật toán Knapsack để gom nhóm các Order Items khớp với tổng giá trị hóa đơn yêu cầu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Finance"
                ],
                "summary": "Phân bổ hóa đơn VAT",
                "parameters": [
                    {
                        "description": "VAT allocation request payload",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.VATAllocationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/inventory/deduct": {
            "post": {
                "description": "Trừ tồn kho theo thuật toán FEFO",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "summary": "Trừ tồn kho FEFO",
                "parameters": [
                    {
                        "description": "Stock deduction request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.DeductStockRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/inventory/receipt": {
            "post": {
                "description": "Nhập kho sản phẩm",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "summary": "Nhập kho",
                "parameters": [
                    {
                        "description": "Stock receipt request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateReceiptRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/inventory/validate": {
            "post": {
                "description": "Validate if stock is available for given items and warehouse",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "summary": "Kiểm tra tồn kho",
                "parameters": [
                    {
                        "description": "Stock validation request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ValidateStockRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/logistics/orders/{id}/shipping": {
            "post": {
                "description": "Gửi API sang hãng vận chuyển để tạo mã vận đơn",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Logistics"
                ],
                "summary": "Tạo vận đơn giao hàng",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/orders": {
            "post": {
                "description": "Tạo đơn hàng, kiểm tra voucher, trừ tồn kho và ghi nhận thanh toán",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Tạo đơn bán hàng",
                "parameters": [
                    {
                        "description": "Create order request payload",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Order"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/promotions/verify": {
            "post": {
                "description": "Xác thực và tính toán số tiền được giảm của Voucher",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Promotions"
                ],
                "summary": "Xác thực mã khuyến mãi",
                "parameters": [
                    {
                        "description": "Verify promotion request payload",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.VerifyPromotionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.VerifyPromotionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/purchasing/orders": {
            "post": {
                "description": "Tạo đơn hàng từ nhà cung cấp",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Purchasing"
                ],
                "summary": "Tạo đơn đặt hàng PO",
                "parameters": [
                    {
                        "description": "Create PO request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreatePurchaseOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.PurchaseOrder"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/webhooks/logistics/status-update": {
            "post": {
                "description": "Hãng vận chuyển gọi API này để báo cáo trạng thái đơn hàng",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Logistics"
                ],
                "summary": "Webhook nhận trạng thái từ GHN",
                "responses": {}
            }
        },
        "/ws/v1/clinic/queue": {
            "get": {
                "description": "Kết nối WebSocket để nhận realtime updates từ queue",
                "tags": [
                    "Clinic"
                ],
                "summary": "WebSocket cho hàng đợi",
                "responses": {}
            }
        }
    },
    "definitions": {
        "domain.Appointment": {
            "type": "object",
            "properties": {
                "appointment_time": {
                    "type": "string"
                },
                "check_in_time": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "doctor_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "patient_id": {
                    "type": "integer"
                },
                "service_type": {
                    "description": "e.g., 'examination'",
                    "type": "string"
                },
                "status": {
                    "description": "'pending', 'waiting', 'completed', 'cancelled'",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.BookAppointmentRequest": {
            "type": "object",
            "required": [
                "appointment_time",
                "doctor_id",
                "patient_id",
                "service_type"
            ],
            "properties": {
                "appointment_time": {
                    "type": "string"
                },
                "doctor_id": {
                    "type": "integer"
                },
                "patient_id": {
                    "type": "integer"
                },
                "service_type": {
                    "type": "string"
                }
            }
        },
        "domain.CheckInRequest": {
            "type": "object",
            "properties": {
                "notes": {
                    "type": "string"
                }
            }
        },
        "domain.CreateOrderRequest": {
            "type": "object",
            "required": [
                "customer_id",
                "items",
                "payment_method",
                "warehouse_id"
            ],
            "properties": {
                "customer_id": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/domain.OrderItemRequest"
                    }
                },
                "payment_method": {
                    "type": "string"
                },
                "voucher_code": {
                    "type": "string"
                },
                "warehouse_id": {
                    "type": "integer"
                }
            }
        },
        "domain.CreatePOItemRequest": {
            "type": "object",
            "required": [
                "product_id",
                "quantity_ordered",
                "unit"
            ],
            "properties": {
                "is_bonus": {
                    "type": "boolean"
                },
                "product_id": {
                    "type": "integer"
                },
                "quantity_ordered": {
                    "type": "number"
                },
                "unit": {
                    "type": "string"
                },
                "unit_price": {
                    "type": "number"
                }
            }
        },
        "domain.CreatePurchaseOrderRequest": {
            "type": "object",
            "required": [
                "items",
                "supplier_id"
            ],
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.CreatePOItemRequest"
                    }
                },
                "supplier_id": {
                    "type": "integer"
                }
            }
        },
        "domain.CreateReceiptRequest": {
            "type": "object",
            "required": [
                "items",
                "warehouse_id"
            ],
            "properties": {
                "items": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/domain.ReceiptItem"
                    }
                },
                "note": {
                    "type": "string"
                },
                "warehouse_id": {
                    "type": "integer"
                }
            }
        },
        "domain.CreateTransactionRequest": {
            "type": "object",
            "required": [
                "amount",
                "flow",
                "fund_account_id"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "description": {
                    "type": "string"
                },
                "flow": {
                    "type": "string"
                },
                "fund_account_id": {
                    "type": "integer"
                },
                "ref_id": {
                    "type": "string"
                },
                "ref_type": {
                    "type": "string"
                }
            }
        },
        "domain.DeductStockRequest": {
            "type": "object",
            "required": [
                "items",
                "warehouse_id"
            ],
            "properties": {
                "items": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/domain.ValidateStockItem"
                    }
                },
                "warehouse_id": {
                    "type": "integer"
                }
            }
        },
        "domain.EarnLoyaltyRequest": {
            "type": "object",
            "required": [
                "amount",
                "customer_id",
                "order_id"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "customer_id": {
                    "type": "integer"
                },
                "order_id": {
                    "type": "integer"
                }
            }
        },
        "domain.Order": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "customer_id": {
                    "type": "integer"
                },
                "delivery_status": {
                    "type": "string"
                },
                "discount_amount": {
                    "type": "number"
                },
                "final_amount": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.OrderItem"
                    }
                },
                "order_code": {
                    "type": "string"
                },
                "payment_method": {
                    "type": "string"
                },
                "payment_status": {
                    "description": "unpaid, paid",
                    "type": "string"
                },
                "status": {
                    "description": "pending, confirmed, completed",
                    "type": "string"
                },
                "total_amount": {
                    "type": "number"
                },
                "tracking_code": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.OrderItem": {
            "type": "object",
            "properties": {
                "conversion_factor": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "order_id": {
                    "type": "integer"
                },
                "product_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "number"
                },
                "total_price": {
                    "type": "number"
                },
                "unit_price": {
                    "type": "number"
                },
                "uom": {
                    "type": "string"
                }
            }
        },
        "domain.OrderItemRequest": {
            "type": "object",
            "required": [
                "product_id",
                "quantity",
                "unit_price",
                "uom"
            ],
            "properties": {
                "product_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "number"
                },
                "unit_price": {
                    "type": "number",
                    "minimum": 0
                },
                "uom": {
                    "type": "string"
                }
            }
        },
        "domain.PurchaseOrder": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.PurchaseOrderItem"
                    }
                },
                "order_code": {
                    "type": "string"
                },
                "status": {
                    "description": "'pending', 'completed', 'cancelled'",
                    "type": "string"
                },
                "supplier_id": {
                    "type": "integer"
                },
                "total_amount": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.PurchaseOrderItem": {
            "type": "object",
            "properties": {
                "base_quantity": {
                    "description": "Quantity in base unit",
                    "type": "number"
                },
                "conversion_factor": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "is_bonus": {
                    "type": "boolean"
                },
                "product_id": {
                    "type": "integer"
                },
                "purchase_order_id": {
                    "type": "integer"
                },
                "quantity_ordered": {
                    "type": "number"
                },
                "unit": {
                    "type": "string"
                },
                "unit_price": {
                    "type": "number"
                }
            }
        },
        "domain.ReceiptItem": {
            "type": "object",
            "required": [
                "batch_code",
                "expiry_date",
                "product_id",
                "quantity"
            ],
            "properties": {
                "batch_code": {
                    "type": "string"
                },
                "expiry_date": {
                    "type": "string"
                },
                "product_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "number"
                },
                "unit_price": {
                    "type": "number"
                }
            }
        },
        "domain.VATAllocationRequest": {
            "type": "object",
            "required": [
                "customer_id",
                "target_amount"
            ],
            "properties": {
                "customer_id": {
                    "type": "integer"
                },
                "target_amount": {
                    "type": "number"
                }
            }
        },
        "domain.ValidateStockItem": {
            "type": "object",
            "required": [
                "product_id",
                "quantity",
                "uom"
            ],
            "properties": {
                "items_per_carton": {
                    "description": "Added for Purchasing",
                    "type": "integer"
                },
                "product_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "number"
                },
                "uom": {
                    "description": "The requested unit of measurement",
                    "type": "string"
                },
                "wholesale_unit": {
                    "description": "Added for Purchasing",
                    "type": "string"
                }
            }
        },
        "domain.ValidateStockRequest": {
            "type": "object",
            "required": [
                "items",
                "warehouse_id"
            ],
            "properties": {
                "items": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/domain.ValidateStockItem"
                    }
                },
                "warehouse_id": {
                    "type": "integer"
                }
            }
        },
        "domain.VerifyPromotionRequest": {
            "type": "object",
            "required": [
                "order_value",
                "voucher_code"
            ],
            "properties": {
                "customer_id": {
                    "type": "integer"
                },
                "order_value": {
                    "type": "number"
                },
                "voucher_code": {
                    "type": "string"
                }
            }
        },
        "domain.VerifyPromotionResponse": {
            "type": "object",
            "properties": {
                "discount_amount": {
                    "type": "number"
                },
                "is_valid": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "promotion_id": {
                    "type": "integer"
                }
            }
        },
        "handlers.AIChatRequest": {
            "type": "object",
            "required": [
                "message"
            ],
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
