/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/ai/chat": {
    /** Gửi câu hỏi cho AI và nhận câu trả lời dạng Server-Sent Events (SSE) */
    post: {
      parameters: {
        body: {
          /** Chat request */
          req: definitions["handlers.AIChatRequest"];
        };
      };
      responses: {
        /** SSE Stream */
        200: {
          schema: string;
        };
      };
    };
  };
  "/api/v1/clinic/appointments": {
    /** Lễ tân tạo lịch hẹn khám bệnh cho bệnh nhân */
    post: {
      parameters: {
        body: {
          /** Book appointment request payload */
          req: definitions["domain.BookAppointmentRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["domain.Appointment"];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: unknown };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: unknown };
        };
      };
    };
  };
  "/api/v1/clinic/appointments/{id}/check-in": {
    /** Lễ tân xác nhận bệnh nhân đã tới và đưa vào hàng đợi chờ khám */
    post: {
      parameters: {
        path: {
          /** Appointment ID */
          id: string;
        };
        body: {
          /** Check-in request payload */
          req?: definitions["domain.CheckInRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: { [key: string]: unknown };
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: unknown };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: unknown };
        };
      };
    };
  };
  "/api/v1/crm/loyalty/earn": {
    /** Cộng điểm cho khách hàng dựa trên giá trị đơn hàng */
    post: {
      parameters: {
        body: {
          /** Earn loyalty request payload */
          req: definitions["domain.EarnLoyaltyRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: { [key: string]: unknown };
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: unknown };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: unknown };
        };
      };
    };
  };
  "/api/v1/finance/transactions": {
    /** Sinh phiếu thu chi, tự động chặn nếu vi phạm luật thuế, chẻ phiếu nếu lệch tiền */
    post: {
      parameters: {
        body: {
          /** Create transaction request payload */
          req: definitions["domain.CreateTransactionRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: { [key: string]: unknown };
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: unknown };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: unknown };
        };
      };
    };
  };
  "/api/v1/finance/vat-allocation": {
    /** Sử dụng thuật toán Knapsack để gom nhóm các Order Items khớp với tổng giá trị hóa đơn yêu cầu */
    post: {
      parameters: {
        body: {
          /** VAT allocation request payload */
          req: definitions["domain.VATAllocationRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: { [key: string]: unknown };
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: unknown };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: unknown };
        };
      };
    };
  };
  "/api/v1/inventory/deduct": {
    /** Trừ tồn kho theo thuật toán FEFO */
    post: {
      parameters: {
        body: {
          /** Stock deduction request */
          req: definitions["domain.DeductStockRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: { [key: string]: unknown };
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: unknown };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: unknown };
        };
      };
    };
  };
  "/api/v1/inventory/receipt": {
    /** Nhập kho sản phẩm */
    post: {
      parameters: {
        body: {
          /** Stock receipt request */
          req: definitions["domain.CreateReceiptRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: { [key: string]: unknown };
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: unknown };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: unknown };
        };
      };
    };
  };
  "/api/v1/inventory/validate": {
    /** Validate if stock is available for given items and warehouse */
    post: {
      parameters: {
        body: {
          /** Stock validation request */
          req: definitions["domain.ValidateStockRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: { [key: string]: unknown };
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: unknown };
        };
      };
    };
  };
  "/api/v1/logistics/orders/{id}/shipping": {
    /** Gửi API sang hãng vận chuyển để tạo mã vận đơn */
    post: {
      parameters: {
        path: {
          /** Order ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: { [key: string]: unknown };
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: unknown };
        };
      };
    };
  };
  "/api/v1/orders": {
    /** Tạo đơn hàng, kiểm tra voucher, trừ tồn kho và ghi nhận thanh toán */
    post: {
      parameters: {
        body: {
          /** Create order request payload */
          req: definitions["domain.CreateOrderRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["domain.Order"];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: unknown };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: unknown };
        };
      };
    };
  };
  "/api/v1/promotions/verify": {
    /** Xác thực và tính toán số tiền được giảm của Voucher */
    post: {
      parameters: {
        body: {
          /** Verify promotion request payload */
          req: definitions["domain.VerifyPromotionRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["domain.VerifyPromotionResponse"];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: unknown };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: unknown };
        };
      };
    };
  };
  "/api/v1/purchasing/orders": {
    /** Tạo đơn hàng từ nhà cung cấp */
    post: {
      parameters: {
        body: {
          /** Create PO request */
          req: definitions["domain.CreatePurchaseOrderRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["domain.PurchaseOrder"];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: unknown };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: unknown };
        };
      };
    };
  };
  "/api/v1/webhooks/logistics/status-update": {
    /** Hãng vận chuyển gọi API này để báo cáo trạng thái đơn hàng */
    post: {
      responses: {};
    };
  };
  "/ws/v1/clinic/queue": {
    /** Kết nối WebSocket để nhận realtime updates từ queue */
    get: {
      responses: {};
    };
  };
}

export interface definitions {
  "domain.Appointment": {
    appointment_time?: string;
    check_in_time?: string;
    created_at?: string;
    doctor_id?: number;
    id?: string;
    patient_id?: number;
    /** @description e.g., 'examination' */
    service_type?: string;
    /** @description 'pending', 'waiting', 'completed', 'cancelled' */
    status?: string;
    updated_at?: string;
  };
  "domain.BookAppointmentRequest": {
    appointment_time: string;
    doctor_id: number;
    patient_id: number;
    service_type: string;
  };
  "domain.CheckInRequest": {
    notes?: string;
  };
  "domain.CreateOrderRequest": {
    customer_id: number;
    items: definitions["domain.OrderItemRequest"][];
    payment_method: string;
    voucher_code?: string;
    warehouse_id: number;
  };
  "domain.CreatePOItemRequest": {
    is_bonus?: boolean;
    product_id: number;
    quantity_ordered: number;
    unit: string;
    unit_price?: number;
  };
  "domain.CreatePurchaseOrderRequest": {
    items: definitions["domain.CreatePOItemRequest"][];
    supplier_id: number;
  };
  "domain.CreateReceiptRequest": {
    items: definitions["domain.ReceiptItem"][];
    note?: string;
    warehouse_id: number;
  };
  "domain.CreateTransactionRequest": {
    amount: number;
    description?: string;
    flow: string;
    fund_account_id: number;
    ref_id?: string;
    ref_type?: string;
  };
  "domain.DeductStockRequest": {
    items: definitions["domain.ValidateStockItem"][];
    warehouse_id: number;
  };
  "domain.EarnLoyaltyRequest": {
    amount: number;
    customer_id: number;
    order_id: number;
  };
  "domain.Order": {
    created_at?: string;
    customer_id?: number;
    delivery_status?: string;
    discount_amount?: number;
    final_amount?: number;
    id?: number;
    items?: definitions["domain.OrderItem"][];
    order_code?: string;
    payment_method?: string;
    /** @description unpaid, paid */
    payment_status?: string;
    /** @description pending, confirmed, completed */
    status?: string;
    total_amount?: number;
    tracking_code?: string;
    updated_at?: string;
  };
  "domain.OrderItem": {
    conversion_factor?: number;
    id?: number;
    order_id?: number;
    product_id?: number;
    quantity?: number;
    total_price?: number;
    unit_price?: number;
    uom?: string;
  };
  "domain.OrderItemRequest": {
    product_id: number;
    quantity: number;
    unit_price: number;
    uom: string;
  };
  "domain.PurchaseOrder": {
    created_at?: string;
    id?: number;
    items?: definitions["domain.PurchaseOrderItem"][];
    order_code?: string;
    /** @description 'pending', 'completed', 'cancelled' */
    status?: string;
    supplier_id?: number;
    total_amount?: number;
    updated_at?: string;
  };
  "domain.PurchaseOrderItem": {
    /** @description Quantity in base unit */
    base_quantity?: number;
    conversion_factor?: number;
    id?: number;
    is_bonus?: boolean;
    product_id?: number;
    purchase_order_id?: number;
    quantity_ordered?: number;
    unit?: string;
    unit_price?: number;
  };
  "domain.ReceiptItem": {
    batch_code: string;
    expiry_date: string;
    product_id: number;
    quantity: number;
    unit_price?: number;
  };
  "domain.VATAllocationRequest": {
    customer_id: number;
    target_amount: number;
  };
  "domain.ValidateStockItem": {
    /** @description Added for Purchasing */
    items_per_carton?: number;
    product_id: number;
    quantity: number;
    /** @description The requested unit of measurement */
    uom: string;
    /** @description Added for Purchasing */
    wholesale_unit?: string;
  };
  "domain.ValidateStockRequest": {
    items: definitions["domain.ValidateStockItem"][];
    warehouse_id: number;
  };
  "domain.VerifyPromotionRequest": {
    customer_id?: number;
    order_value: number;
    voucher_code: string;
  };
  "domain.VerifyPromotionResponse": {
    discount_amount?: number;
    is_valid?: boolean;
    message?: string;
    promotion_id?: number;
  };
  "handlers.AIChatRequest": {
    message: string;
  };
}

export interface operations {}

export interface external {}
